### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by nguyenhuutri1620vn** [MatheusCordeiroP/Dinosaur-IA-Genetic-#1]
help me, please :'(

**Comment by MatheusCordeiroP** [comment]
sorry for late to reply.
That project was made on unity game engine, so you can run it there.
You need to download Unity, so you can open the project there and run as if it was a game.
Since it was made some time ago, I don't remember the exact unity version necessary to run, but i suppose almost any version newer than 2019 must run.

Tell me if you still having any trouble!

**Comment by MatheusCordeiroP** [comment]
If you just want to run the project, and not editing codes or scenes, now you can just download the "game file".

https://github.com/MatheusCordeiroP/dinosaur-genetic-algorithm/blob/main/Game.rar

and run the "Dinossauro IA.exe" file in any windows device.
